# Generated by Django 4.1.4 on 2023-02-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="st_age",
            field=models.IntegerField(),
        ),
    ]
